package cn.yongnian.seckill.mapper;

import cn.yongnian.seckill.model.SeckillGoods;
import cn.yongnian.seckill.model.SeckillGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SeckillGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_goods
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    long countByExample(SeckillGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_goods
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    int deleteByExample(SeckillGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_goods
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_goods
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    int insert(SeckillGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_goods
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    int insertSelective(SeckillGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_goods
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    List<SeckillGoods> selectByExampleWithRowbounds(SeckillGoodsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_goods
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    List<SeckillGoods> selectByExample(SeckillGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_goods
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    SeckillGoods selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_goods
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    int updateByExampleSelective(@Param("record") SeckillGoods record, @Param("example") SeckillGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_goods
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    int updateByExample(@Param("record") SeckillGoods record, @Param("example") SeckillGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_goods
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    int updateByPrimaryKeySelective(SeckillGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_goods
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    int updateByPrimaryKey(SeckillGoods record);
}