package cn.yongnian.seckill.model;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.user_id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.goods_id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.delivery_address_id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    private Long deliveryAddressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.goods_name
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.goods_count
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    private Integer goodsCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.goods_price
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    private BigDecimal goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_channel
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    private Byte orderChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.status
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.gmt_create
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.gmt_pay
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    private Date gmtPay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.id
     *
     * @return the value of order_info.id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.id
     *
     * @param id the value for order_info.id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.user_id
     *
     * @return the value of order_info.user_id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.user_id
     *
     * @param userId the value for order_info.user_id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.goods_id
     *
     * @return the value of order_info.goods_id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.goods_id
     *
     * @param goodsId the value for order_info.goods_id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.delivery_address_id
     *
     * @return the value of order_info.delivery_address_id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public Long getDeliveryAddressId() {
        return deliveryAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.delivery_address_id
     *
     * @param deliveryAddressId the value for order_info.delivery_address_id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public void setDeliveryAddressId(Long deliveryAddressId) {
        this.deliveryAddressId = deliveryAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.goods_name
     *
     * @return the value of order_info.goods_name
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.goods_name
     *
     * @param goodsName the value for order_info.goods_name
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.goods_count
     *
     * @return the value of order_info.goods_count
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public Integer getGoodsCount() {
        return goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.goods_count
     *
     * @param goodsCount the value for order_info.goods_count
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public void setGoodsCount(Integer goodsCount) {
        this.goodsCount = goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.goods_price
     *
     * @return the value of order_info.goods_price
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.goods_price
     *
     * @param goodsPrice the value for order_info.goods_price
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_channel
     *
     * @return the value of order_info.order_channel
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public Byte getOrderChannel() {
        return orderChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_channel
     *
     * @param orderChannel the value for order_info.order_channel
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public void setOrderChannel(Byte orderChannel) {
        this.orderChannel = orderChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.status
     *
     * @return the value of order_info.status
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.status
     *
     * @param status the value for order_info.status
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.gmt_create
     *
     * @return the value of order_info.gmt_create
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.gmt_create
     *
     * @param gmtCreate the value for order_info.gmt_create
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.gmt_pay
     *
     * @return the value of order_info.gmt_pay
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public Date getGmtPay() {
        return gmtPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.gmt_pay
     *
     * @param gmtPay the value for order_info.gmt_pay
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public void setGmtPay(Date gmtPay) {
        this.gmtPay = gmtPay;
    }
}