package cn.yongnian.seckill.model;

public class SeckillOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_order.id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_order.user_id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_order.order_id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_order.goods_id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    private Long goodsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_order.id
     *
     * @return the value of seckill_order.id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_order.id
     *
     * @param id the value for seckill_order.id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_order.user_id
     *
     * @return the value of seckill_order.user_id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_order.user_id
     *
     * @param userId the value for seckill_order.user_id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_order.order_id
     *
     * @return the value of seckill_order.order_id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_order.order_id
     *
     * @param orderId the value for seckill_order.order_id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_order.goods_id
     *
     * @return the value of seckill_order.goods_id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_order.goods_id
     *
     * @param goodsId the value for seckill_order.goods_id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }
}