package cn.yongnian.seckill.model;

import java.math.BigDecimal;
import java.util.Date;

public class SeckillGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_goods.id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_goods.goods_id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_goods.seckill_price
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    private BigDecimal seckillPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_goods.seckill_stock
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    private Integer seckillStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_goods.start_date
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_goods.end_date
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    private Date endDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_goods.id
     *
     * @return the value of seckill_goods.id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_goods.id
     *
     * @param id the value for seckill_goods.id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_goods.goods_id
     *
     * @return the value of seckill_goods.goods_id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_goods.goods_id
     *
     * @param goodsId the value for seckill_goods.goods_id
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_goods.seckill_price
     *
     * @return the value of seckill_goods.seckill_price
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public BigDecimal getSeckillPrice() {
        return seckillPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_goods.seckill_price
     *
     * @param seckillPrice the value for seckill_goods.seckill_price
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public void setSeckillPrice(BigDecimal seckillPrice) {
        this.seckillPrice = seckillPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_goods.seckill_stock
     *
     * @return the value of seckill_goods.seckill_stock
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public Integer getSeckillStock() {
        return seckillStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_goods.seckill_stock
     *
     * @param seckillStock the value for seckill_goods.seckill_stock
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public void setSeckillStock(Integer seckillStock) {
        this.seckillStock = seckillStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_goods.start_date
     *
     * @return the value of seckill_goods.start_date
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_goods.start_date
     *
     * @param startDate the value for seckill_goods.start_date
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_goods.end_date
     *
     * @return the value of seckill_goods.end_date
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_goods.end_date
     *
     * @param endDate the value for seckill_goods.end_date
     *
     * @mbg.generated Sun May 24 13:27:10 CEST 2020
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
}